name: Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  test_mapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: '>> unit & performance tests for mapper <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          testRunOnly: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: perf-test

  publish_mapper:
    needs: [test_mapper]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: '>> publish mapper package to pub.dev <<'
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          force: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: mapper
      - name: 'Commit release tag'
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_adapter:
    needs: [publish_mapper]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        adapter: ["flutter", "built", "fixnum", "mobx"]

    steps:
      - uses: actions/checkout@main
      - run: cp -f ./mapper/LICENSE ./adapters/${{ matrix.adapter }}/LICENSE
      - name: '>> test & publish adapter / ${{ matrix.adapter }} <<'
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: adapters/${{ matrix.adapter }}
      - name: 'Commit release tag'
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
